"""YOLOv8 fine-tuning wrapper.

Thin adapter around ``ultralytics.YOLO.train()``. Exists so callers don't
scatter ultralytics keyword arguments across scripts, tests can inject a
mock trainer, and the hyperparameter set is one dataclass rather than
twelve positional arguments.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

log = logging.getLogger(__name__)


@dataclass
class TrainingConfig:
    """All hyperparameters in one place. Matches ``configs/training.yaml``."""
    weights: str = "yolov8s.pt"
    data_yaml: Path = Path("output/dataset/carla_pursuit/dataset.yaml")
    epochs: int = 30
    patience: int = 10
    imgsz: int = 640
    batch: int = -1                  # -1 = ultralytics auto-sizer (falls back on OOM)
    optimizer: str = "AdamW"
    seed: int = 42
    deterministic: bool = True
    half: bool = True                # fp16
    # Augmentation — disable what doesn't make sense for aerial; keep what does.
    mosaic: float = 0.0              # splices 4 images, unnatural road graphs
    degrees: float = 0.0             # aerial is pre-oriented at −75° pitch
    hsv_h: float = 0.015
    hsv_s: float = 0.7
    hsv_v: float = 0.4
    scale: float = 0.5
    translate: float = 0.1
    # Output locations
    project: str = "output/weights"  # artifacts root
    name: str = "run_v1"             # subdir under project
    device: str = "cuda:0"
    # Misc pass-through — keep a dict for future additions without churn.
    extra: dict = field(default_factory=dict)


def build_dataset_yaml(
    dataset_root: Path,
    train_runs: list[str],
    val_runs: list[str],
    out_path: Path,
) -> Path:
    """Write an Ultralytics YOLO dataset YAML that references per-run images.

    The YAML points at two text files (``train.txt`` / ``val.txt``) listing
    absolute image paths. Ultralytics resolves the label for each image by
    swapping ``images/`` with ``labels/`` and the extension — our directory
    layout (``run_XX/images/frame_YYYY.jpg`` + ``run_XX/labels/frame_YYYY.txt``)
    matches this convention by construction.
    """
    dataset_root = Path(dataset_root)
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    train_txt = out_path.parent / "train.txt"
    val_txt = out_path.parent / "val.txt"

    def write_list(runs: list[str], dest: Path) -> int:
        paths: list[str] = []
        for run in runs:
            run_images = dataset_root / run / "images"
            for img in sorted(run_images.glob("*.jpg")):
                paths.append(str(img.resolve()))
        dest.write_text("\n".join(paths) + "\n")
        return len(paths)

    n_train = write_list(train_runs, train_txt)
    n_val = write_list(val_runs, val_txt)

    yaml_contents = (
        f"# Auto-generated by skycop.cv.training.build_dataset_yaml\n"
        f"path: {dataset_root.resolve()}\n"
        f"train: {train_txt.resolve()}\n"
        f"val: {val_txt.resolve()}\n"
        f"nc: 1\n"
        f"names: ['vehicle']\n"
    )
    out_path.write_text(yaml_contents)

    log.info(
        "dataset yaml written to %s (train=%d images, val=%d images)",
        out_path, n_train, n_val,
    )
    return out_path


def train_detector(cfg: TrainingConfig):
    """Run ``ultralytics.YOLO.train()`` with the config. Returns the results object."""
    from ultralytics import YOLO

    log.info(
        "training: weights=%s epochs=%d imgsz=%d batch=%s device=%s",
        cfg.weights, cfg.epochs, cfg.imgsz, cfg.batch, cfg.device,
    )

    model = YOLO(cfg.weights)
    results = model.train(
        data=str(cfg.data_yaml),
        epochs=cfg.epochs,
        patience=cfg.patience,
        imgsz=cfg.imgsz,
        batch=cfg.batch,
        optimizer=cfg.optimizer,
        seed=cfg.seed,
        deterministic=cfg.deterministic,
        half=cfg.half,
        mosaic=cfg.mosaic,
        degrees=cfg.degrees,
        hsv_h=cfg.hsv_h,
        hsv_s=cfg.hsv_s,
        hsv_v=cfg.hsv_v,
        scale=cfg.scale,
        translate=cfg.translate,
        project=cfg.project,
        name=cfg.name,
        device=cfg.device,
        exist_ok=True,                # overwrite existing run dir
        verbose=True,
        **cfg.extra,
    )
    return results, model


def best_weights_path(cfg: TrainingConfig) -> Path:
    """Ultralytics convention: project/name/weights/best.pt."""
    return Path(cfg.project) / cfg.name / "weights" / "best.pt"
